// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9x4mAEDbKa1juh_MaYB3dWoI2SEQQdk8',
    appId: '1:883644336879:ios:40f4dd781445580a71e91a',
    messagingSenderId: '883644336879',
    projectId: 'goalflow-anh-linh-2026',
    storageBucket: 'goalflow-anh-linh-2026.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9x4mAEDbKa1juh_MaYB3dWoI2SEQQdk8',
    appId: '1:883644336879:ios:40f4dd781445580a71e91a',
    messagingSenderId: '883644336879',
    projectId: 'goalflow-anh-linh-2026',
    storageBucket: 'goalflow-anh-linh-2026.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNFiIbwXrJ7O2bV-pc1ljlR6iU7H5naOs',
    appId: '1:883644336879:web:d4467a2f00fa16af71e91a',
    messagingSenderId: '883644336879',
    projectId: 'goalflow-anh-linh-2026',
    authDomain: 'goalflow-anh-linh-2026.firebaseapp.com',
    storageBucket: 'goalflow-anh-linh-2026.firebasestorage.app',
    measurementId: 'G-VBV56M0XQB',
  );
}
